analysis_results:
- analysis_reason: タイトル・内容からその他政策に分類
  new_label: その他政策
  number: 823
  title: 著作権セクションのリンク切れ修正（三浦さん提案）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 822
  title: Eugeneさん提案：目次に「国防」項目を追加し、サイバーセキュリティ関連の議論を提起
- analysis_reason: タイトル・内容から経済財政に分類
  new_label: 経済財政
  number: 821
  title: 「海底資源開発の推進」に関する項目を追加
- analysis_reason: タイトル・内容から経済財政に分類
  new_label: 経済財政
  number: 820
  title: インフラ整備の項目追加とメンテナンス重視の提案
- analysis_reason: タイトル・内容から教育に分類
  new_label: 教育
  number: 817
  title: 目次への「入試制度改革（仮）」項目追加による高校教育の改善提案
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 816
  title: 「チームみらいについて」に反科学的見解を持つ人物を許容しない方針を明記
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 812
  title: 匿名ユーザーによる提案：「国政政党成立後100日プラン」にAIによる進捗自動開示の仕組みを明記
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 810
  title: 【さとぷぅさん提案】マニフェストに「皇室のあり方」の項目追加
- analysis_reason: タイトル・内容から福祉に分類
  new_label: 福祉
  number: 809
  title: AIの倫理的利用と安全確保に関する政策の追加 by bob
- analysis_reason: タイトル・内容からデジタル民主主義に分類
  new_label: デジタル民主主義
  number: 807
  title: 憲法改正：有権者起点の国民投票による改正発議プロセスの提案
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 759
  title: 政策マニフェスト：「チームみらいについて」の記述を修正 (匿名ユーザー提案)
- analysis_reason: タイトル・内容からその他政策に分類
  new_label: その他政策
  number: 756
  title: マニフェストへの、やさしい日本語の併記案
- analysis_reason: タイトル・内容から経済財政に分類
  new_label: 経済財政
  number: 755
  title: 暗号資産税制の簡素化によるWeb3技術活用の推進 by snow
- analysis_reason: タイトル・内容から教育に分類
  new_label: 教育
  number: 753
  title: 目次：『採用における学歴要件の適正化』の議論のための項目追加
- analysis_reason: タイトル・内容から教育に分類
  new_label: 教育
  number: 752
  title: 教育現場における専門家配置と育成に関する提案
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 750
  title: 高齢者の医療費負担に関する方針の明確化 by jj
- analysis_reason: タイトル・内容から教育に分類
  new_label: 教育
  number: 719
  title: 子育て支援に関する記述の拡充提案 by オリゼ
- analysis_reason: タイトル・内容から教育に分類
  new_label: 教育
  number: 718
  title: 介護従事者の待遇改善に関する提案
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 710
  title: エンジニア以外でも直感的にトップページを認識できるよう、README.md以外のファイル名（例：00_はじめに.md）を検討する提案
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 709
  title: 【README.md】財源に関する課題とエネルギー政策の注釈を追加（犀川 茂さんのご提案）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 708
  title: 【あなごさん提案】マニフェストに新章『誰もが取り残されない社会へ』を追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 706
  title: 行政改革における国産技術活用の推進とデジタル主権確立に関する提案
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 704
  title: 家庭教師AIを活用した児童保護の強化について
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 700
  title: 多様な意見の共存と建設的対話の促進に関する提案
- analysis_reason: タイトル・内容から教育に分類
  new_label: 教育
  number: 397
  title: ステップ2への追記：個々の能力と多様性を尊重した責任のあり方の検討
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 299
  title: 匿名ユーザー提案：生活保護制度の改革に関する具体的な指針の追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 297
  title: 匿名ユーザーによる「その他重要分野」への追記提案
- analysis_reason: タイトル・内容からデジタル民主主義に分類
  new_label: デジタル民主主義
  number: 296
  title: これからの『みらい』を担う子供たちでも理解できるマニフェストにしませんか？（ゆき提案）
- analysis_reason: タイトル・内容から福祉に分類
  new_label: 福祉
  number: 294
  title: NaNさんによる政策提案：高齢者の健康インセンティブ制度の導入
- analysis_reason: タイトル・内容から行政改革に分類
  new_label: 行政改革
  number: 291
  title: 行政改革：ブロックチェーン技術活用による戸籍制度改革の提案
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 290
  title: おぜきさんによる農業政策に関する提案
- analysis_reason: タイトル・内容から教育に分類
  new_label: 教育
  number: 283
  title: 婚姻費用・養育費の債権譲渡に関する法整備の提案 (匿名ユーザー)
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 279
  title: FLOWさんによる提案：基軸通貨のデジタル化推進と税制効率化
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 278
  title: 政治資金の透明性向上：地方議員・国会議員の経費におけるコーポレートカード使用義務化（NaNさんより）
- analysis_reason: タイトル・内容から教育に分類
  new_label: 教育
  number: 275
  title: 【匿名ユーザー提案】年少扶養控除の復活と基礎控除の物価連動制導入による子育て支援強化
- analysis_reason: タイトル・内容から行政改革に分類
  new_label: 行政改革
  number: 274
  title: とらこさんの提案：行政改革における働き方改革の明記
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 269
  title: 提案：社会的養護経験者支援と児童福祉改革の項目の新設
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 264
  title: NaNさん提案：マニフェストへの多角的視点の導入と具体例の追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 263
  title: FLOWさん提案：「親権ライセンス制度」の導入について
- analysis_reason: タイトル・内容から行政改革に分類
  new_label: 行政改革
  number: 262
  title: 子育て支援策の強化：デジタル技術を活用した子どもの安全確保とネット上の有害情報対策
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 260
  title: 養育費・婚姻費用の未払い問題への対応策を追加
- analysis_reason: タイトル・内容から経済財政に分類
  new_label: 経済財政
  number: 258
  title: 新聞への軽減税率適用中止を経済財政政策に追加
- analysis_reason: タイトル・内容から子育てに分類
  new_label: 子育て
  number: 257
  title: 【冷静さん提案】マニフェスト冒頭の改善：キャッチコピーと子育て支援策要約の追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 240
  title: 政策提案：同性婚の法制化に関する提案をマニフェストに追記
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 234
  title: 介護分野におけるデジタル技術活用の検討（かいごテクさん提案）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 232
  title: ステップ４：テクノロジーで支える新しい家族のかたち の追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 230
  title: 医療制度改革に関する新規提案の追加（Dr.おねえ）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 197
  title: 政策マニフェスト（README.md）の改善提案 by ショウ
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 195
  title: READMEにFLOW氏の提案原文へのリンクを追加
- analysis_reason: タイトル・内容からデジタル民主主義に分類
  new_label: デジタル民主主義
  number: 191
  title: README.md更新：デジタル民主主義における未成年者の政治参加の検討について追記（にしおさん提案）
batch_info:
  batch_name: final_100_batch2
  batch_size: 50
  pr_range: '#191-#823'
  prs:
  - 823
  - 822
  - 821
  - 820
  - 817
  - 816
  - 812
  - 810
  - 809
  - 807
  - 759
  - 756
  - 755
  - 753
  - 752
  - 750
  - 719
  - 718
  - 710
  - 709
  - 708
  - 706
  - 704
  - 700
  - 397
  - 299
  - 297
  - 296
  - 294
  - 291
  - 290
  - 283
  - 279
  - 278
  - 275
  - 274
  - 269
  - 264
  - 263
  - 262
  - 260
  - 258
  - 257
  - 240
  - 234
  - 232
  - 230
  - 197
  - 195
  - 191
summary:
  label_distribution:
    その他政策: 2
    デジタル民主主義: 3
    ビジョン: 27
    子育て: 1
    教育: 8
    福祉: 2
    経済財政: 4
    行政改革: 3
  total_analyzed: 50
