analysis_results:
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1560
  title: 【たけしさん提案】産業政策：航空機・船舶産業への投資を通じた防衛力強化と技術維持
- analysis_reason: タイトル・内容から行政改革に分類
  new_label: 行政改革
  number: 1547
  title: 匿名ユーザーによる提案：AI失業SEのリスキリングと公務員登用によるDX推進
- analysis_reason: タイトル・内容からデジタル民主主義に分類
  new_label: デジタル民主主義
  number: 1540
  title: デジタル民主主義推進のため、政策解説アプリ開発及び国会アプリ構想を明記
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1535
  title: 行政改革における国・都道府県・市町村の連携と役割分担に関する視点の追加 by 阿井上夫
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1531
  title: フリーアドレス登校制度の提案と目次への追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1525
  title: README.mdの更新：親子関係の明確化に関する議論提起
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1523
  title: akiさん提案：AIを活用した『セーフティスポンジ構想』の追加
- analysis_reason: タイトル・内容からその他政策に分類
  new_label: その他政策
  number: 1511
  title: 「README.md」への「マニフェスト執筆のガイドライン」リンク追加
- analysis_reason: タイトル・内容から教育に分類
  new_label: 教育
  number: 1509
  title: 【畑 裕基さん提案】オフライン及び未成年者の政策参加方法の拡充について
- analysis_reason: タイトル・内容から教育に分類
  new_label: 教育
  number: 1508
  title: 【せさん改善提案】少子化対策：晩婚化・晩産化への問題提起と若者の早期自立支援の重要性
- analysis_reason: タイトル・内容からデジタル民主主義に分類
  new_label: デジタル民主主義
  number: 1505
  title: 首相公選制に関する政策提言追加と目次更新
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1503
  title: 農業政策に関する新規提案（農協改革を中心として）
- analysis_reason: タイトル・内容から教育に分類
  new_label: 教育
  number: 1502
  title: 子どもの権利保護の徹底を求めるマニフェスト改善提案
- analysis_reason: タイトル・内容から医療に分類
  new_label: 医療
  number: 1493
  title: 某氏より：医療制度と消費税に関する提案（市販薬の免税化等）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1476
  title: 提案：経済社会の根本構造に関する問題提起と唯一の解決策である政府通貨発行
- analysis_reason: タイトル・内容からデジタル民主主義に分類
  new_label: デジタル民主主義
  number: 1465
  title: 国家再興のための緊急包括政策提言（ねこレベル-9999さん ご提案）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1459
  title: 教育：すべての子どもに高度な学びへのアクセスを保障するマニフェスト改訂
- analysis_reason: タイトル・内容から福祉に分類
  new_label: 福祉
  number: 1458
  title: 【小山氏提案】住宅投機抑制及び居住安定化促進法案（仮称）の追加について
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1456
  title: 科学技術の項目に防災・減災への活用を追記（阿井上夫さん提案）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1452
  title: 食料政策に関する新規提案および目次更新（mayabreaさんより）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1450
  title: README.mdの「チームみらいについて」の記述をより具体的に改善（かあさん提案）
- analysis_reason: タイトル・内容から経済財政に分類
  new_label: 経済財政
  number: 1447
  title: 農業政策の追加（匿名希望さん提案）
- analysis_reason: タイトル・内容から行政改革に分類
  new_label: 行政改革
  number: 1445
  title: 【小山さん提案】ギグワーク・フリーランス等の適正報酬保障に関する法案の追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1442
  title: AI戦略推進の司令塔「J-STeP」構想をマニフェストに提言
- analysis_reason: タイトル・内容から行政改革に分類
  new_label: 行政改革
  number: 1438
  title: AIとデータを活用したセーフティネット強化策の追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1436
  title: ステップ3への行政改革提言の追加（担当：小山）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1432
  title: 匿名ユーザー様による環境政策に関する3件の提案
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1430
  title: エネルギー政策における原子力再稼働目標の再検討依頼（cactusさんご提案）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1426
  title: 農業政策の新規提案：米不足時代に対応する持続可能な農業生産基盤の確立（提案者：みかん）
- analysis_reason: タイトル・内容から行政改革に分類
  new_label: 行政改革
  number: 1422
  title: デジタル障害者手帳の検討状況を追記
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1259
  title: 【はろ提案】マニフェスト全体方針および教育分野の記述改善
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1256
  title: README.md：「いどばたシステム」に関する利用者の声と改善への言及を追記
- analysis_reason: タイトル・内容から教育に分類
  new_label: 教育
  number: 1252
  title: こんにちはさん発案：公共銀行構想によるマニフェスト改善提案
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1248
  title: 政策提案：歴史的文化財の保護と平和学習の推進に関する提案
- analysis_reason: タイトル・内容から経済財政に分類
  new_label: 経済財政
  number: 1247
  title: 産業政策に二輪車高速料金の負担軽減を追記
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1246
  title: りすくさん提案：ワクチン接種履歴管理システムの構築と非デジタル対応者への配慮
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1244
  title: こんにちはさん提案：マニフェストの目次に「社会全体のバランスの最適化」の章を追加
- analysis_reason: タイトル・内容から行政改革に分類
  new_label: 行政改革
  number: 1240
  title: りすく様提案：高齢者の運転免許制度に関する検討項目の追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1239
  title: kenjiさんによるステップ1への経済財政項目の追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1238
  title: デジタル民主主義の項目に被選挙権年齢と供託金引き下げに関する記述を追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1233
  title: 匿名ユーザーによる「その他重要分野についての政策・ビジョン」への追加提案およびシステム改善提案
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1231
  title: りすくさん提案：防衛力強化のための国産ミサイル戦略の追加
- analysis_reason: タイトル・内容から科学技術に分類
  new_label: 科学技術
  number: 1228
  title: マニフェスト改善への参加を促進するための包括的提案
- analysis_reason: タイトル・内容から教育に分類
  new_label: 教育
  number: 1227
  title: 教育方針の更新：AI家庭教師導入と通学強制廃止による個別最適化された学習環境の実現（ベーシックインカムによる経済的自由と意思決定の尊重も視野に）
- analysis_reason: タイトル・内容から福祉に分類
  new_label: 福祉
  number: 1226
  title: 氷河期世代への支援策に関するマニフェスト改訂提案（高橋めぐみ）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1216
  title: ぽぽさんによるマニフェスト改善提案：行政手続きの効率化と全体目標の明確化
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1215
  title: AV新法見直しに関する提案（りすくさんより）
- analysis_reason: タイトル・内容から教育に分類
  new_label: 教育
  number: 1213
  title: ステイフーリッシュさん提案：社会人の学び直し支援（リカレント教育）の強化
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1208
  title: README.md のチームビジョン及び産業政策に関する記述の更新提案（柴田優呼）
- analysis_reason: タイトル・内容から教育に分類
  new_label: 教育
  number: 1207
  title: 教育改革の進め方に関する提案（★さん提案）
batch_info:
  batch_name: next2_100_batch1
  batch_size: 50
  pr_range: '#1207-#1560'
  prs:
  - 1560
  - 1547
  - 1540
  - 1535
  - 1531
  - 1525
  - 1523
  - 1511
  - 1509
  - 1508
  - 1505
  - 1503
  - 1502
  - 1493
  - 1476
  - 1465
  - 1459
  - 1458
  - 1456
  - 1452
  - 1450
  - 1447
  - 1445
  - 1442
  - 1438
  - 1436
  - 1432
  - 1430
  - 1426
  - 1422
  - 1259
  - 1256
  - 1252
  - 1248
  - 1247
  - 1246
  - 1244
  - 1240
  - 1239
  - 1238
  - 1233
  - 1231
  - 1228
  - 1227
  - 1226
  - 1216
  - 1215
  - 1213
  - 1208
  - 1207
summary:
  label_distribution:
    その他政策: 1
    デジタル民主主義: 3
    ビジョン: 28
    医療: 1
    教育: 7
    福祉: 2
    科学技術: 1
    経済財政: 2
    行政改革: 5
  total_analyzed: 50
