analysis_results:
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1034
  title: 教育政策の改善：オンライン課外活動の充実に関するtakuさんのご提案
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1031
  title: 医療政策に関する提案：医療DX推進による効率的な医療提供体制の構築 by 正人
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1020
  title: 【匿名ユーザー提案】「103万円の壁」解消に向けた所得税制の具体的な改善案
- analysis_reason: タイトル・内容から経済財政に分類
  new_label: 経済財政
  number: 1019
  title: ステップ3経済財政に暗号資産税制の検討項目を追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1016
  title: 外国人労働者・移民に関する記述の追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1012
  title: kaizu氏による教育改革提案：教育の3つの軸と特別教員免許制度の導入
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1000
  title: 政策目次に「デジタル文化財の保護とアクセシビリティ向上」を追加
- analysis_reason: タイトル・内容から教育に分類
  new_label: 教育
  number: 993
  title: 教育政策の具体化提案（国語力強化・JSL教育充実化）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 986
  title: '[みらい提案] 暗号資産税制に関する検討課題の追加'
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 984
  title: 政策提案：ステップ３の産業分野に「与信制度の見直し」に関する項目を追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 981
  title: マニフェスト改善提案（目次構成の変更：外交・安全保障、介護項目の追加・整理 by kamei）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 973
  title: マニフェスト冒頭に教育に関する包括的理念を追記（匿名ユーザーさん提案）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 966
  title: 文化政策と歴史教育の推進に関する提案
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 960
  title: 刑法175条（わいせつ物頒布等の罪）の廃止を目指す提案（りすく提案）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 958
  title: マニフェストの目次に「社会保障」の項目を追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 955
  title: たばこ対策の強化に関する政策提案
- analysis_reason: タイトル・内容からデジタル民主主義に分類
  new_label: デジタル民主主義
  number: 953
  title: README.mdの更新：デジタル民主主義における若者の政治参加促進の提案 (あささん提案)
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 949
  title: テツさんの提案：デジタル社会における個人情報保護とセキュリティの強化
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 941
  title: 子育て支援の拡充：NIPT等検査に関する提案（あささんより）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 936
  title: 【オカモト様ご提案】母子家庭支援（児童扶養手当所得制限緩和・公営住宅優先入居等）の議論明記
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 934
  title: 【大地提案】個人の楽しみのための自家醸造解禁に関する項目追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 930
  title: 畑 裕基さん提案：ステップ１教育に生涯学習とデジタルスキル習得の観点を追加
- analysis_reason: タイトル・内容から教育に分類
  new_label: 教育
  number: 927
  title: 政策提案：高度専門分野における権威的評価制度の導入検討
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 923
  title: 畑 裕基さんの提案：医療分野における生成AI活用の具体化
- analysis_reason: タイトル・内容から福祉に分類
  new_label: 福祉
  number: 922
  title: インボイス制度 -年収1,000万円未満の免税事業者への支援の検討-
- analysis_reason: タイトル・内容から行政改革に分類
  new_label: 行政改革
  number: 921
  title: 行政改革：地方移住・二拠点生活支援のための情報マッチングシステム構築の提案
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 919
  title: README目次更新：土曜祝日の振替休日に関する項目追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 914
  title: 重要社会基盤整備と法制度見直しに関する提案（とまとさん）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 915
  title: 匿名ユーザー提案：教育評価における客観性・公平性向上のための抜本的改革案
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 910
  title: 医療・介護分野におけるロボティクス活用推進のためのマニフェスト改訂案
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 909
  title: いちやなぎさん提案：開かれた投票制度の実現について
- analysis_reason: タイトル・内容からエネルギーに分類
  new_label: エネルギー
  number: 907
  title: 禁止事項の具体例追記と表現改善（与那嶺信さん提案）
- analysis_reason: タイトル・内容から経済財政に分類
  new_label: 経済財政
  number: 905
  title: 文化発信と国際理解の促進による新たな価値創造の提案（パスタさんより）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 899
  title: 【一般男性さんご提案】チームみらいのAIに対する基本姿勢の明確化
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 895
  title: 教育：AIを活用した家庭との連携強化策の追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 894
  title: 【Makiさん提案】政策案への結婚支援およびマッチングアプリ開発項目の追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 893
  title: 生涯学習AIの導入による、誰一人取り残さない学びの機会創出
- analysis_reason: タイトル・内容から福祉に分類
  new_label: 福祉
  number: 885
  title: 地域交通の充実に関する政策提案（MIKIKOさんより）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 881
  title: じゅんさん提案：「高齢化社会対策」の項目新設と「終末期医療における意思の尊重」について
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 878
  title: エネルギー政策における原子力推進の明記
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 877
  title: 外国人労働者の権利擁護に関する項目追加のご提案（とっちさんより）
- analysis_reason: タイトル・内容からその他政策に分類
  new_label: その他政策
  number: 871
  title: 【かつしかさん提案】マニフェスト冒頭へのサマリー追加による可読性向上
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 867
  title: README.md：ステップ１に氷河期世代支援の項目を追加（高久浩次さんの提案）
- analysis_reason: タイトル・内容から福祉に分類
  new_label: 福祉
  number: 858
  title: ステップ1への「自立した生活の支援」追加とAI活用による高齢者・福祉従事者支援策の提案
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 854
  title: 働き方改革：週初めの始業時間柔軟化による生産性・幸福度向上（FUGAさん提案）
- analysis_reason: タイトル・内容からデジタル民主主義に分類
  new_label: デジタル民主主義
  number: 851
  title: アライさん提案：「子ども票」「次世代優先投票枠」の構想を追加し、その背景や意図を解説
- analysis_reason: タイトル・内容からその他政策に分類
  new_label: その他政策
  number: 848
  title: 日本国憲法の現代語訳推進：国民全てによる理解と主体的な関与を目指して (格調高い版)
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 841
  title: 目次に「【🧑‍🤝‍🧑】未来の人口政策（宇宙時代に向けて）」を追加 (内容更新)
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 839
  title: おさたまさんのご提案：マニフェストに「選挙制度と情報戦略の改革」の章を追加
- analysis_reason: タイトル・内容からデジタル民主主義に分類
  new_label: デジタル民主主義
  number: 836
  title: いどばたシステムの企業活用に関する追記提案 by hrm311
batch_info:
  batch_name: final_100_batch1
  batch_size: 50
  pr_range: '#836-#1034'
  prs:
  - 1034
  - 1031
  - 1020
  - 1019
  - 1016
  - 1012
  - 1000
  - 993
  - 986
  - 984
  - 981
  - 973
  - 966
  - 960
  - 958
  - 955
  - 953
  - 949
  - 941
  - 936
  - 934
  - 930
  - 927
  - 923
  - 922
  - 921
  - 919
  - 914
  - 915
  - 910
  - 909
  - 907
  - 905
  - 899
  - 895
  - 894
  - 893
  - 885
  - 881
  - 878
  - 877
  - 871
  - 867
  - 858
  - 854
  - 851
  - 848
  - 841
  - 839
  - 836
summary:
  label_distribution:
    その他政策: 2
    エネルギー: 1
    デジタル民主主義: 3
    ビジョン: 36
    教育: 2
    福祉: 3
    経済財政: 2
    行政改革: 1
  total_analyzed: 50
