analysis_results:
- analysis_reason: タイトル・内容から経済財政に分類
  new_label: 経済財政
  number: 1205
  title: 【りすくさん提案】車両盗難対策の厳罰化をマニフェストに追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1204
  title: nipponniさんの提案による政策目次への重要課題の包括的追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1203
  title: ジェンダーギャップ解消に向けた具体的な政策（地方自治体職員への研修等）の追加提案（はるさんより）
- analysis_reason: タイトル・内容からその他政策に分類
  new_label: その他政策
  number: 1199
  title: 変更履歴機能の追加（オーブさん提案）
- analysis_reason: タイトル・内容から行政改革に分類
  new_label: 行政改革
  number: 1198
  title: AI活用による行政効率化の提案（まるさん）
- analysis_reason: タイトル・内容から行政改革に分類
  new_label: 行政改革
  number: 1194
  title: 医療DXの推進とデータ活用に関する提案
- analysis_reason: タイトル・内容から行政改革に分類
  new_label: 行政改革
  number: 1189
  title: みつさん提案：働き方・休み方の改善（祝日増による週休3・4日制推進）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1183
  title: とまとさん提案：科学技術分野における革新的廃棄物処理技術と国民参加型イノベーション推進の検討項目追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1181
  title: 【煮凝りさん提案】同性婚の法制化に関する記述を更新し、不合理な区別の解消を目指す
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1178
  title: マニフェスト改善提案：国民の声の反映強化、氷河期世代支援、及び統治機構改革の検討
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1177
  title: 重要政策分野に関する項目追加の提案（安楽死制度・人工林管理）
- analysis_reason: タイトル・内容から経済財政に分類
  new_label: 経済財政
  number: 1174
  title: 政策マニフェストの目次に「インフラ長寿命化」の項目を追加
- analysis_reason: タイトル・内容からエネルギーに分類
  new_label: エネルギー
  number: 1169
  title: Cakeさんより：変更提案後のコミュニケーションについて追記
- analysis_reason: タイトル・内容から行政改革に分類
  new_label: 行政改革
  number: 1168
  title: 子育て家庭への包括的支援：AIによる親の心理・スキル向上サポートと支援が必要な子どもの早期発見・支援体制の拡充
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1166
  title: 【ジョン・スミスさんご提案】マニフェスト改善提案（年金問題および政策の時間軸明確化）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1164
  title: 人口増加社会を実現するための真の教育、社会改革
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1163
  title: AI熟議プラットフォーム構想の追加
- analysis_reason: タイトル・内容から教育に分類
  new_label: 教育
  number: 1162
  title: ふむさんの提案に基づき、日本人の生活再建と政策透明化をマニフェストに明記
- analysis_reason: タイトル・内容からデジタル民主主義に分類
  new_label: デジタル民主主義
  number: 1160
  title: README.mdへの行政改革に関する追記と、その背景について(まると様ご提案)
- analysis_reason: タイトル・内容からデジタル民主主義に分類
  new_label: デジタル民主主義
  number: 1159
  title: 候補者の能力に関する定量的な情報開示✒についての提案
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1157
  title: 医療政策（混合診療導入検討）の重要性確認と議論深化のお願い（あきらさんより）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1156
  title: 【人類様ご提案】チームみらいの目指す社会像の明確化
- analysis_reason: タイトル・内容から行政改革に分類
  new_label: 行政改革
  number: 1149
  title: README.md 目次更新：税務申告簡素化による起業支援と行政DX推進案の追加（いどたさん提案）
- analysis_reason: タイトル・内容から[システム]に分類
  new_label: '[システム]'
  number: 1148
  title: 提案の可視化に関する記述の追加（小山提案）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1144
  title: マニフェスト改善提案：「その他重要分野」への「地域交通の持続可能性」項目の追加
- analysis_reason: タイトル・内容から行政改革に分類
  new_label: 行政改革
  number: 1139
  title: 【小山氏提案】再投資促進税の導入による国内投資促進と経済活性化について
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1138
  title: 専門用語を分かりやすくし、より多くの人に開かれたマニフェストを目指す改善提案
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1135
  title: 塚本豊様ご提案：人間社会シミュレータの具体的な活用について
- analysis_reason: タイトル・内容から行政改革に分類
  new_label: 行政改革
  number: 1127
  title: 目次構成の改善：分野横断的な政策のまとめリンクを追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1118
  title: 【政策改善案】ポイ捨てゼロ社会の実現：次世代へつなぐ美しい日本のために
- analysis_reason: タイトル・内容から行政改革に分類
  new_label: 行政改革
  number: 1116
  title: README.md：ワクチン接種記録の転記負担軽減に関する具体例を追記（よっぴーさんの提案）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1115
  title: マニフェスト改善プロセス及び基本理念の明確化に関する提案（匿名ユーザー）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1114
  title: 選択的夫婦別姓制度の導入に関する提案（かわごえさん提案）
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1109
  title: 【strickぇさん提案】行政改革：障害者手帳・自立支援医療受給者証のマイナンバーカード統合
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1106
  title: ユーザーaさんによるデジタルインフラ整備に関する提案
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1098
  title: AI倫理とAGIガバナンスに関する基本姿勢の追加と目次修正 by t.a
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1093
  title: 政策ビジョンにデジタル円を活用した税制改革の推進を追加 (nkさん提案)
- analysis_reason: タイトル・内容からその他政策に分類
  new_label: その他政策
  number: 1087
  title: NHK会長の国民審査制度に関する提案をマニフェストに追記
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1084
  title: README.mdの「チームみらいについて」セクションに具体例を追加 by 鈴麻呂
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1083
  title: JA改革による農業競争力強化と食料安全保障の確立提案 by たけく19810630
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1082
  title: 「チームみらいについて」セクションの充実化提案（鈴麻呂さんご提案）
- analysis_reason: タイトル・内容から教育に分類
  new_label: 教育
  number: 1069
  title: 使用経済システムの導入提案
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1064
  title: 提案：喫煙環境改善のため「ステップ1」に「生活環境」項目を追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1063
  title: りすくさんによる憲法改正に関する提案の追加
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1061
  title: kayobonさんによるデジタル活用支援と情報リテラシー向上に関する提案
- analysis_reason: タイトル・内容から福祉に分類
  new_label: 福祉
  number: 1054
  title: 木造住宅の耐震等級3義務化による建築基準法改正案
- analysis_reason: タイトル・内容から福祉に分類
  new_label: 福祉
  number: 1045
  title: README.mdの「変更提案の受付方針」を具体的にしました👍
- analysis_reason: タイトル・内容から経済財政に分類
  new_label: 経済財政
  number: 1041
  title: 結婚と家族形成に関する新たな視点の追加提案
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1039
  title: いまを生きる「自分らしさ」が花開く社会へ🌸：多様な生き方を認め合い、公正な仕組みを育む
- analysis_reason: タイトル・内容からビジョンに分類
  new_label: ビジョン
  number: 1035
  title: akiさんの提案：チーム紹介にAIによる税金ムダ削減の文言を追加
batch_info:
  batch_name: next2_100_batch2
  batch_size: 50
  pr_range: '#1035-#1205'
  prs:
  - 1205
  - 1204
  - 1203
  - 1199
  - 1198
  - 1194
  - 1189
  - 1183
  - 1181
  - 1178
  - 1177
  - 1174
  - 1169
  - 1168
  - 1166
  - 1164
  - 1163
  - 1162
  - 1160
  - 1159
  - 1157
  - 1156
  - 1149
  - 1148
  - 1144
  - 1139
  - 1138
  - 1135
  - 1127
  - 1118
  - 1116
  - 1115
  - 1114
  - 1109
  - 1106
  - 1098
  - 1093
  - 1087
  - 1084
  - 1083
  - 1082
  - 1069
  - 1064
  - 1063
  - 1061
  - 1054
  - 1045
  - 1041
  - 1039
  - 1035
summary:
  label_distribution:
    '[システム]': 1
    その他政策: 2
    エネルギー: 1
    デジタル民主主義: 2
    ビジョン: 29
    教育: 2
    福祉: 2
    経済財政: 3
    行政改革: 8
  total_analyzed: 50
